http:
    host: 'localhost'
    port: 31000

db:
    mysql:
        url: 'localhost'
        port: 3306
        type: 'mysql'
        password: 'password'
        username: 'root'
        database: 'socketchat'
        logging: true
